services:
  quake3:
    build: .
    command: +exec server.cfg
    stdin_open: true
    tty: true
    volumes:
      - ./pak0.pk3:/home/quake/ioquake3/baseq3/pak0.pk3
      - ./server.cfg:/home/quake/ioquake3/baseq3/server.cfg
      - ./instagib:/home/quake/ioquake3/instagib
    ports:
      - "27960:27960/udp"
